import { PrismaClient, PropertyType, ListingType, PropertyStatus } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  const propertiesData = [
    // Bangalore Properties
    {
      title: "Modern 3BHK Apartment in Koramangala",
      description: "Beautiful 3BHK apartment in the heart of Koramangala with modern amenities and excellent connectivity.",
      propertyType: PropertyType.APARTMENT,
      listingType: ListingType.SALE,
      status: PropertyStatus.ACTIVE,
      streetAddress: "123, Koramangala Industrial Layout",
      city: "Bangalore",
      state: "Karnataka",
      zipCode: "560034",
      country: "India",
      latitude: 12.9352,
      longitude: 77.6129,
      price: 12500000,
      bedrooms: 3,
      bathrooms: 2.5,
      squareFeet: 1800,
      yearBuilt: 2020,
      features: ["Swimming Pool", "Gym", "24/7 Security", "Parking"],
      amenities: ["Club House", "Garden", "Play Area"],
      appliances: ["Refrigerator", "Washing Machine", "AC", "Water Purifier"],
      flooring: ["Marble", "Wooden"],
      heating: ["Central Heating"],
      cooling: ["Split AC"],
      listedDate: new Date(),
    },
    {
      title: "Luxury Villa in Whitefield",
      description: "Spacious luxury villa with garden and pool in premium Whitefield location.",
      propertyType: PropertyType.VILLA,
      listingType: ListingType.SALE,
      status: PropertyStatus.ACTIVE,
      streetAddress: "45, Prestige Golf Course Road",
      city: "Bangalore",
      state: "Karnataka",
      zipCode: "560066",
      country: "India",
      latitude: 12.9716,
      longitude: 77.6826,
      price: 25000000,
      bedrooms: 4,
      bathrooms: 4,
      squareFeet: 3500,
      yearBuilt: 2018,
      features: ["Swimming Pool", "Garden", "Garage", "Security"],
      amenities: ["Tennis Court", "Club House", "Spa"],
      appliances: ["Home Theater", "Smart Home System", "Solar Panels"],
      flooring: ["Granite", "Marble"],
      heating: ["Radiant Floor Heating"],
      cooling: ["Central AC"],
      listedDate: new Date(),
    },
    {
      title: "Affordable 2BHK in HSR Layout",
      description: "Well-designed 2BHK apartment in peaceful HSR Layout with excellent infrastructure.",
      propertyType: PropertyType.APARTMENT,
      listingType: ListingType.RENT,
      status: PropertyStatus.ACTIVE,
      streetAddress: "789, HSR Sector 2",
      city: "Bangalore",
      state: "Karnataka",
      zipCode: "560102",
      country: "India",
      latitude: 12.9139,
      longitude: 77.6315,
      price: 25000,
      bedrooms: 2,
      bathrooms: 2,
      squareFeet: 1200,
      yearBuilt: 2019,
      features: ["Balcony", "Parking", "Lift"],
      amenities: ["Gym", "Children Play Area"],
      appliances: ["Water Purifier", "Gas Stove"],
      flooring: ["Vitrified Tiles"],
      heating: ["Room Heater"],
      cooling: ["Split AC"],
      listedDate: new Date(),
    },
    {
      title: "Premium Penthouse in Indiranagar",
      description: "Stunning penthouse with panoramic views and premium finishes in posh Indiranagar.",
      propertyType: PropertyType.PENTHOUSE,
      listingType: ListingType.SALE,
      status: PropertyStatus.ACTIVE,
      streetAddress: "101, Indiranagar Double Road",
      city: "Bangalore",
      state: "Karnataka",
      zipCode: "560038",
      country: "India",
      latitude: 12.9742,
      longitude: 77.6457,
      price: 35000000,
      bedrooms: 3,
      bathrooms: 3,
      squareFeet: 2800,
      yearBuilt: 2021,
      features: ["Terrace", "Swimming Pool", "Gym", "Concierge"],
      amenities: ["Spa", "Restaurant", "Conference Room"],
      appliances: ["Home Automation", "Wine Cellar", "Steam Room"],
      flooring: ["Italian Marble", "Hardwood"],
      heating: ["Underfloor Heating"],
      cooling: ["VRV System"],
      listedDate: new Date(),
    },
    {
      title: "Heritage Home in Malleshwaram",
      description: "Charming heritage home with traditional architecture and modern amenities.",
      propertyType: PropertyType.HOUSE,
      listingType: ListingType.SALE,
      status: PropertyStatus.ACTIVE,
      streetAddress: "22, Malleshwaram 8th Cross",
      city: "Bangalore",
      state: "Karnataka",
      zipCode: "560003",
      country: "India",
      latitude: 13.0097,
      longitude: 77.5598,
      price: 18000000,
      bedrooms: 4,
      bathrooms: 3,
      squareFeet: 2200,
      yearBuilt: 1995,
      features: ["Courtyard", "Traditional Architecture", "Garden"],
      amenities: ["Library", "Study Room"],
      appliances: ["Vintage Collection", "Antique Furniture"],
      flooring: ["Teak Wood", "Stone"],
      heating: ["Fireplace"],
      cooling: ["Cross Ventilation"],
      listedDate: new Date(),
    },

    // Mumbai Properties
    {
      title: "Sea-facing Apartment in Bandra West",
      description: "Luxurious sea-facing apartment with stunning views of the Arabian Sea.",
      propertyType: PropertyType.APARTMENT,
      listingType: ListingType.SALE,
      status: PropertyStatus.ACTIVE,
      streetAddress: "505, Bandra West",
      city: "Mumbai",
      state: "Maharashtra",
      zipCode: "400050",
      country: "India",
      latitude: 19.0613,
      longitude: 72.8361,
      price: 45000000,
      bedrooms: 3,
      bathrooms: 3,
      squareFeet: 2200,
      yearBuilt: 2017,
      features: ["Sea View", "Balcony", "Parking", "Security"],
      amenities: ["Swimming Pool", "Gym", "Club House"],
      appliances: ["Home Theater", "Modular Kitchen", "Water Softener"],
      flooring: ["Italian Marble", "Granite"],
      heating: ["Central Heating"],
      cooling: ["Central AC"],
      listedDate: new Date(),
    },
    {
      title: "Premium Flat in Worli",
      description: "Premium flat in the prestigious Worli area with excellent connectivity.",
      propertyType: PropertyType.APARTMENT,
      listingType: ListingType.RENT,
      status: PropertyStatus.ACTIVE,
      streetAddress: "15, Worli Naka",
      city: "Mumbai",
      state: "Maharashtra",
      zipCode: "400018",
      country: "India",
      latitude: 18.9972,
      longitude: 72.8131,
      price: 65000,
      bedrooms: 2,
      bathrooms: 2,
      squareFeet: 1400,
      yearBuilt: 2020,
      features: ["City View", "Balcony", "Parking"],
      amenities: ["Gym", "Swimming Pool", "Kids Play Area"],
      appliances: ["Air Purifier", "Water Purifier", "Modular Kitchen"],
      flooring: ["Vitrified Tiles", "Marble"],
      heating: ["Room Heater"],
      cooling: ["Split AC"],
      listedDate: new Date(),
    },
    {
      title: "Bungalow in Juhu",
      description: "Spacious bungalow in the upscale Juhu locality near the beach.",
      propertyType: PropertyType.HOUSE,
      listingType: ListingType.SALE,
      status: PropertyStatus.ACTIVE,
      streetAddress: "22, Juhu Scheme",
      city: "Mumbai",
      state: "Maharashtra",
      zipCode: "400049",
      country: "India",
      latitude: 19.0840,
      longitude: 72.8330,
      price: 85000000,
      bedrooms: 5,
      bathrooms: 5,
      squareFeet: 5000,
      yearBuilt: 2005,
      features: ["Garden", "Pool", "Garage", "Driver's Quarter"],
      amenities: ["Guest House", "Staff Quarter", "Lawn"],
      appliances: ["Home Automation", "Generator", "Water Softener"],
      flooring: ["Marble", "Wooden"],
      heating: ["Central Heating"],
      cooling: ["Central AC"],
      listedDate: new Date(),
    },
    {
      title: "Studio Apartment in Lower Parel",
      description: "Compact studio apartment ideal for young professionals in central Mumbai.",
      propertyType: PropertyType.APARTMENT,
      listingType: ListingType.RENT,
      status: PropertyStatus.ACTIVE,
      streetAddress: "303, Peninsula Business Park",
      city: "Mumbai",
      state: "Maharashtra",
      zipCode: "400013",
      country: "India",
      latitude: 19.0190,
      longitude: 72.8311,
      price: 35000,
      bedrooms: 1,
      bathrooms: 1,
      squareFeet: 700,
      yearBuilt: 2019,
      features: ["Compact Design", "Parking", "Lift"],
      amenities: ["Co-working Space", "Cafeteria", "Gym"],
      appliances: ["Microwave", "Refrigerator", "AC"],
      flooring: ["Engineered Wood"],
      heating: ["Room Heater"],
      cooling: ["Split AC"],
      listedDate: new Date(),
    },
    {
      title: "Duplex in Powai",
      description: "Modern duplex apartment in the growing Powai IT hub.",
      propertyType: PropertyType.APARTMENT,
      listingType: ListingType.SALE,
      status: PropertyStatus.ACTIVE,
      streetAddress: "44, Hiranandani Gardens",
      city: "Mumbai",
      state: "Maharashtra",
      zipCode: "400076",
      country: "India",
      latitude: 19.1197,
      longitude: 72.9034,
      price: 32000000,
      bedrooms: 3,
      bathrooms: 2.5,
      squareFeet: 2000,
      yearBuilt: 2018,
      features: ["Duplex Design", "Balcony", "Parking", "Security"],
      amenities: ["Swimming Pool", "Gym", "Tennis Court"],
      appliances: ["Home Automation", "Modular Kitchen", "Water Purifier"],
      flooring: ["Granite", "Wooden"],
      heating: ["Central Heating"],
      cooling: ["Central AC"],
      listedDate: new Date(),
    },

    // Delhi Properties
    {
      title: "Luxury House in Lutyens' Delhi",
      description: "Grand house in the prestigious Lutyens' Delhi area with colonial architecture.",
      propertyType: PropertyType.HOUSE,
      listingType: ListingType.SALE,
      status: PropertyStatus.ACTIVE,
      streetAddress: "12, Akbar Road",
      city: "New Delhi",
      state: "Delhi",
      zipCode: "110001",
      country: "India",
      latitude: 28.6094,
      longitude: 77.1975,
      price: 120000000,
      bedrooms: 6,
      bathrooms: 6,
      squareFeet: 8000,
      yearBuilt: 1985,
      features: ["Historical Value", "Large Garden", "Garage", "Staff Quarters"],
      amenities: ["Library", "Drawing Room", "Dining Hall"],
      appliances: ["Vintage Collection", "Antique Furniture", "Generator"],
      flooring: ["Marble", "Teak Wood"],
      heating: ["Fireplace"], 
      cooling: ["Central AC"],
      listedDate: new Date(),
    },
    {
      title: "2BHK Apartment in Connaught Place",
      description: "Well-located 2BHK apartment in the heart of Connaught Place.",
      propertyType: PropertyType.APARTMENT,
      listingType: ListingType.RENT,
      status: PropertyStatus.ACTIVE,
      streetAddress: "77, Block A, Connaught Place",
      city: "New Delhi",
      state: "Delhi",
      zipCode: "110001",
      country: "India",
      latitude: 28.6304,
      longitude: 77.2177,
      price: 50000,
      bedrooms: 2,
      bathrooms: 2,
      squareFeet: 1300,
      yearBuilt: 2015,
      features: ["Central Location", "Balcony", "Parking"],
      amenities: ["Gym", "Security", "Lift"],
      appliances: ["Modular Kitchen", "Water Purifier", "AC"],
      flooring: ["Vitrified Tiles", "Marble"],
      heating: ["Room Heater"],
      cooling: ["Split AC"],
      listedDate: new Date(),
    },
    {
      title: "Villa in Golf Course Extension",
      description: "Premium villa in Gurgaon's Golf Course Extension with modern amenities.",
      propertyType: PropertyType.VILLA,
      listingType: ListingType.SALE,
      status: PropertyStatus.ACTIVE,
      streetAddress: "15, Golf Course Ext Rd",
      city: "Gurgaon",
      state: "Haryana",
      zipCode: "122002",
      country: "India",
      latitude: 28.4595,
      longitude: 77.0263,
      price: 65000000,
      bedrooms: 4,
      bathrooms: 4,
      squareFeet: 4000,
      yearBuilt: 2019,
      features: ["Private Garden", "Swimming Pool", "Garage", "Security"],
      amenities: ["Club House", "Gym", "Spa"],
      appliances: ["Home Automation", "Solar Panels", "Water Softener"],
      flooring: ["Italian Marble", "Wooden"],
      heating: ["Underfloor Heating"],
      cooling: ["Central AC"],
      listedDate: new Date(),
    },
    {
      title: "Affordable 1BHK in Dwarka",
      description: "Budget-friendly 1BHK apartment in well-planned Dwarka sector.",
      propertyType: PropertyType.APARTMENT,
      listingType: ListingType.SALE,
      status: PropertyStatus.ACTIVE,
      streetAddress: "202, Sector 8, Dwarka",
      city: "New Delhi",
      state: "Delhi",
      zipCode: "110075",
      country: "India",
      latitude: 28.5847,
      longitude: 77.0330,
      price: 4500000,
      bedrooms: 1,
      bathrooms: 1,
      squareFeet: 650,
      yearBuilt: 2021,
      features: ["Balcony", "Parking", "Lift"],
      amenities: ["Children Play Area", "Community Center"],
      appliances: ["Gas Stove", "Water Purifier"],
      flooring: ["Vitrified Tiles"],
      heating: ["Room Heater"],
      cooling: ["Split AC"],
      listedDate: new Date(),
    },
    {
      title: "Farmhouse in Alwar",
      description: "Beautiful farmhouse near Delhi with organic farm and sustainable living features.",
      propertyType: PropertyType.FARMHOUSE,
      listingType: ListingType.SALE,
      status: PropertyStatus.ACTIVE,
      streetAddress: "Rural Road, Behror",
      city: "Alwar",
      state: "Rajasthan",
      zipCode: "301406",
      country: "India",
      latitude: 27.9654,
      longitude: 76.5825,
      price: 25000000,
      bedrooms: 3,
      bathrooms: 2,
      squareFeet: 2500,
      lotSizeAcres: 5,
      yearBuilt: 2010,
      features: ["Organic Farm", "Solar Power", "Rainwater Harvesting", "Pond"],
      amenities: ["Greenhouse", "Compost Pit", "Well", "Storage"],
      appliances: ["Solar Panels", "Water Pump", "Tractor"],
      flooring: ["Stone", "Brick"],
      heating: ["Biomass Stove"],
      cooling: ["Natural Ventilation"],
      listedDate: new Date(),
    }
  ];

  for (const propertyData of propertiesData) {
    await prisma.property.create({
      data: propertyData
    });
  }

  console.log('Database seeded with 15 properties!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });