import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import fs from 'fs';
import path from 'path';

export interface UncleReportData {
  propertyTitle: string;
  propertyAddress: string;
  totalScore: number;
  verdict: string; // "BUY", "AVOID", "CONSIDER"
  agentAnalyses: {
    agentName: string;
    score: number;
    reasoning: string[];
  }[];
}

export class ReportGeneratorService {

  async generateUncleReport(data: UncleReportData): Promise<Uint8Array> {
    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage();
    const { width, height } = page.getSize();
    const fontSize = 12;
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    let yPosition = height - 50;

    // TITLE
    page.drawText('The Uncle Report', {
      x: 50,
      y: yPosition,
      size: 24,
      font: fontBold,
      color: rgb(0, 0, 0),
    });
    yPosition -= 40;

    // PROPERTY DETAILS
    page.drawText(`Property: ${data.propertyTitle}`, { x: 50, y: yPosition, size: 14, font: fontBold });
    yPosition -= 20;
    page.drawText(`Address: ${data.propertyAddress}`, { x: 50, y: yPosition, size: 12, font: font });
    yPosition -= 40;

    // VERDICT BOX
    const verdictColor = data.verdict === 'BUY' ? rgb(0, 0.5, 0) : (data.verdict === 'AVOID' ? rgb(0.8, 0, 0) : rgb(0.8, 0.6, 0));
    page.drawRectangle({
      x: 50,
      y: yPosition - 10,
      width: width - 100,
      height: 60,
      color: verdictColor,
      opacity: 0.1,
    });

    page.drawText(`FINAL VERDICT: ${data.verdict} (${data.totalScore}/100)`, {
      x: 70,
      y: yPosition + 15,
      size: 18,
      font: fontBold,
      color: verdictColor,
    });
    yPosition -= 80;

    // AGENT BREAKDOWN
    page.drawText('Agent Analysis Breakdown:', { x: 50, y: yPosition, size: 16, font: fontBold });
    yPosition -= 30;

    for (const analysis of data.agentAnalyses) {
      if (yPosition < 100) {
        // Add new page if running out of space
        // (Simplified logic: just stop writing for now to keep it safe)
        break;
      }

      page.drawText(`${analysis.agentName}: ${analysis.score}/100`, { x: 50, y: yPosition, size: 12, font: fontBold });
      yPosition -= 15;

      for (const reason of analysis.reasoning) {
        page.drawText(`• ${reason}`, { x: 60, y: yPosition, size: 10, font: font });
        yPosition -= 12;
      }
      yPosition -= 10; // Spacing between agents
    }

    // FOOTER
    page.drawText('Generated by REST-iN-U AI Swarm', {
      x: 50,
      y: 30,
      size: 10,
      font: font,
      color: rgb(0.5, 0.5, 0.5),
    });

    const pdfBytes = await pdfDoc.save();
    return pdfBytes;
  }
}

export const reportGeneratorService = new ReportGeneratorService();
