apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: restinu

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: restinu-platform

images:
  - name: ghcr.io/restinu/restinu-backend
    newTag: latest
  - name: ghcr.io/restinu/restinu-frontend
    newTag: latest
